cart/urls.py
from django.conf.urls import url
from cart import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'cart'

urlpatterns = [
    url(r'^cart_add/(\d+)/$',views.cart_add,name='cart_add'),
    url(r'^cart_remove/(\d+)/$',views.cart_remove,name='cart_remove'),
    url(r'^cart_detail/$',views.cart_detail,name='cart_detail'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path
from django import urls
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from mystore import views

app_name = 'mystore'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^product_detail/(\d+)/$', views.product_detail, name='product_detail'),
    url(r'^register/$',views.register,name='register'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^login/$',views.user_login,name='login'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoponline/urls.py
from django.contrib import admin
from django.urls import path
from django import urls
from django.conf.urls.static import static
from django.conf import settings
from mystore import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name= 'index'),
    path('cart/', urls.include('cart.urls')),
    path('mystore/', urls.include('mystore.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

mystore/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=264,unique=True)
    fee = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to = "images/")

    def __str__(self):
        return str(self.name)

#Tao class UserProfileInfor
class UserProfileInfo(models.Model):
    #create relationship from this class to User
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #add any more attribute you want
    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to = "images/", blank=True)

    def __str__(self):
        return self.user.username

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]
class CardAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label= 'Số lượng', choices = PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required = False, widget = forms.HiddenInput)

mystore/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    #porfolio = forms.URLField(required = False)
    picture = forms.ImageField(required = False)
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio','picture')

cart/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST
from mystore.models import Product
from .cart import Cart
from .forms import CardAddProductForm
from django.shortcuts import *
# Create your views here.
@require_POST
def cart_add(request, product_id = None):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    form = CardAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product = product, quantity = cd['quantity'], update_quantity =cd['update'])
    print(cart)
    return redirect('cart:cart_detail')

def cart_remove(request, product_id = None):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CardAddProductForm(initial={'quantity':item['quantity'], 'update': True})
    return render(request, 'mystore/cart_detail.html', {'cart':cart})

def cart_update(request, product_id = None):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    cart.update(product)
    return redirect('cart:cart_detail')

mystore/views.py
from django.shortcuts import render
from mystore.models import Product, UserProfileInfo
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from cart.forms import *
from mystore.forms import *
# Create your views here.
def index(request):
    pro_list = Product.objects.order_by('name')
    pro_dict = {"products":pro_list }
    return render(request, "mystore/index.html", context=pro_dict)

def product_detail(request, id = None):
    product = Product.objects.get(pk=id)
    cart_product_form = CardAddProductForm()
    return render(request, 'mystore/product_detail.html', context= {'product': product, 'cart_product_form':cart_product_form })

def register(request):
    registered = False
    if request.method == "POST":
        form_user = UserForm(data = request.POST)
        form_por = UserProfileInfoForm(data = request.POST)
        if form_user.is_valid() and form_por.is_valid():
            user = form_user.save()
            user.set_password(user.password)
            user.save()
            profile = form_por.save(commit = False)
            profile.user = user
            print(request.FILES)
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(form_user.errors, form_por.errors)
    else:
        form_user = UserForm()
        form_por = UserProfileInfoForm()
    return render(request, "mystore/registration.html", {'user_form':form_user,\
        'profile_form': form_por, 'registered': registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                result = "Chào bạn " + username
                return render(request, "mystore/index.html", {"result":result})
        else:
            print("Không đăng nhập được")
            print("Username: {} and password: {}".format(username, password))
            login_result = "Username và password không hợp lệ"
            return render(request, "mystore/login.html",{"login_result": login_result})
    else:
        return render(request, "mystore/login.html")

@login_required
def user_logout(request):
    logout(request)
    result = "Bạn đã đăng xuất. Vui lòng chọn 'Đăng nhập'"
    return render(request, "mystore/index.html", {"result":result})

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
     <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
    <body>
    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'mystore:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mystore:register' %}">Đăng ký </a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'mystore:logout' %}"> Đăng xuất </a></li>
      {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'mystore:login' %}"> Đăng nhập </a></li>
      {% endif %}

      <li class="nav-item">
        <a href="{% url 'cart:cart_detail'%}"><img src = "{% static "imgs/cart.png"%}"  width="50" height="40"></a>
      </li>
      <li class="cart">
      {% if cart %}
        <a class="nav-link" href="{% url 'cart:cart_detail'%}">
        Giỏ hàng có {{cart|length}} sản phẩm , VNĐ: {{cart.get_total_fee}}</a>
        {% else %}
        Giỏ hàng đang trống
        {% endif %}
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="imgs/1.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="imgs/2.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
</div>
        <div class="container">
            {% block body_block %}
            <!-- Anything outsite of this will be inherited if you extend! -->
            {% endblock %}
            </div>
            <!-- Footer -->
                <footer class="py-5 bg-dark">
            <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
        </div>
        <!-- /.container -->
        </footer>
        <!-- Bootstrap core JavaScript -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

templates/mystore/cart_detail.html
{% extends "base.html" %}
{% block body_block %}
    {% load staticfiles %}
    <div class="container"></div>
    <h1>Thông tin giỏ hàng</h1>
    <table class="table">
        <thead class="danger">
            <th>Sản phẩm</th>
            <th>Tên sản phẩm</th>
            <th>Số lượng</th>
            <th>Đơn giá (vnđ)</th>
            <th>Thành tiền (vnđ)</th>
            <th>Xóa</th>
        </thead>
        <tbody>
            {% for item in cart %}
                <tr class="success">
                    <td>
                        <a href="{% url 'mystore:product_detail'
                        item.product.pk%}" ><img src="{{item.product.image.url}}" width="200" height="200"></a>
                    </td>
                    <td>{{item.product.name}}</td>
                    <td>
                        <form action = "{% url 'cart:cart_add' item.product.pk%}" method = "POST">
                            {{item.update_quantity_form.quantity}}
                            {{item.update_quantity_form.update}}
                            <input type ="submit" value = "Cập nhật"/>
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>{{item.fee}}</td>
                    <td>{{item.total_fee}}</td>
                    <td><a href="{% url 'cart:cart_remove' item.product.pk%}">Xóa</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

templates/mystore/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
  {% load staticfiles %}
<!-- Page Features -->
  <div class="row text-center">
    {% if products %}
      {% for value in products %}
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card text-center" style="width: 18rem;">
            <img class="card-img-top" src="{{value.image.url}}" alt="{{value.name}}">
            <div class="card-body">
              <h4 class="card-title">{{value.name}}</h4>
              <p class="card-text">{{value.description}}<br/>{{value.fee}} vnđ</p>
            </div>
            <div>
              <a href="{% url 'mystore:product_detail' value.pk%}" class='btn btnprimary' style="float: center;" > Xem thêm </a>
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif%}
    {% if result %}
      <h1 class="card-text">{{result}}</h1>
    {% endif %}
  </div>
{% endblock %}

templates/mystore/login.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    {% load staticfiles %}
    <div class="container">
        <h1>Đăng nhập</h1>
        <form method="POST" action="{% url 'mystore:login' %}">
            <table>
                <tr><td>
                    <lable for="username">Username:</lable></td>
                    <td><input type="text" name="username" placeholder="Enter username">
                </td></tr>
                <tr>
                    <td><lable for="password">Password:</lable></td>
                    <td><input type="password" name="password" placeholder="Enter password"></td>
                </tr>
                <tr><td colspan="2" align="center">
                    <input type="submit" class="btn btn-primary" value="Submit">
                </td></tr>
            </table>
            {% csrf_token %}
        </form>
        <!--
        {% if login_result %}
        <h4>{{login_result}}</h4>
        {% endif %}
        -->
    </div>
    <div class="container"><p style="color:red">{{login_result}}</p></div>
{% endblock %}

templates/mystore/product_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    {% load staticfiles %}
    <!-- Page Features -->
    <div class="row text-center">
        {% if product %}
            <div class="container">
                <div class="card text-center">
                    <img class="card-img-top" src="{{product.image.url}}"
                    alt="{{product.name}}" width="350" height="350"/>
                    <div class="card-body">
                        <h4 class="card-title">{{product.name}}</h4>
                        <p class="card-text">{{product.description}}<br/>{{product.fee}} vnđ</p>
                    </div>
                    <div>
                        <form action = "{% url 'cart:cart_add' product.pk %}" method = "POST">
                            {{cart_product_form}}
                            {% csrf_token %}
                            <div class = "card-footer">
                                <input type="submit" value="Them vao gio hang" class = "btn btn-primary"
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        {% endif%}
    </div>
{% endblock %}

templates/mystore/registration.html
{% extends "base.html" %}
    {% load staticfiles %}
    {% block body_block %}
        <div class="container">
            {% if registered %}
                <h3>Bạn đã đăng ký thành công.</h3>
            {% else %}
                <h3>Điền vào form đăng ký</h3>
                <form method="POST" enctype="multipart/form-data">
                    <table>
                        {% for field in user_form %}
                            <tr><td>{{field.label}} </td>
                            <td>{{field}}</td></tr>
                        {% endfor %}
                        {% for field1 in profile_form %}
                            <tr><td>{{field1.label}} </td>
                            <td>{{field1}}</td></tr>
                        {% endfor %}
                        {% csrf_token %}
                        <tr><td colspan='2' align="center">
                        <input type="submit" class="btn btn-primary" value="Đăng ký">
                        </td></tr>
                    </table>
                </form>
            {% endif %}
        </div>
    {% endblock %}